# [TODO] can bind to piano type if desired as well

from .a import A_0  #   ===========
from .a import As0  #      ========
from .b import B_0  #   ===========
from .c import C_0  #   ===========
from .c import Cs0  #      ========
from .d import D_0  #   ===========
from .d import Ds0  #      ========
from .e import E_0  #   ===========
from .f import F_0  #   ===========
from .f import Fs0  #      ========
from .g import G_0  #   ===========
from .g import Gs0  #      ========
from .a import A_1  #   ===========
from .a import As1  #      ========
from .b import B_1  #   ===========
from .c import C_1  #   ===========
from .c import Cs1  #      ========
from .d import D_1  #   ===========
from .d import Ds1  #      ========
from .e import E_1  #   ===========
from .f import F_1  #   ===========
from .f import Fs1  #      ========
from .g import G_1  #   ===========
from .g import Gs1  #      ========
from .a import A_2  #   ===========
from .a import As2  #      ========
from .b import B_2  #   ===========
from .c import C_2  #   ===========
from .c import Cs2  #      ========
from .d import D_2  #   ===========
from .d import Ds2  #      ========
from .e import E_2  #   ===========
from .f import F_2  #   ===========
from .f import Fs2  #      ========
from .g import G_2  #   ===========
from .g import Gs2  #      ========
from .a import A_3  #   ===========
from .a import As3  #      ========
from .b import B_3  #   ===========
from .c import C_3  #   ===========
from .c import Cs3  #      ========
from .d import D_3  #   ===========
from .d import Ds3  #      ========
from .e import E_3  #   ===========
from .f import F_3  #   ===========
from .f import Fs3  #      ========
from .g import G_3  #   ===========
from .g import Gs3  #      ========
from .a import A_4  #   ===========
from .a import As4  #      ========
from .b import B_4  #   ===========
from .c import C_4  #   ===========
from .c import Cs4  #      ========
from .d import D_4  #   ===========
from .d import Ds4  #      ========
from .e import E_4  #   ===========
from .f import F_4  #   ===========
from .f import Fs4  #      ========
from .g import G_4  #   ===========
from .g import Gs4  #      ========
from .a import A_5  #   ===========
from .a import As5  #      ========
from .b import B_5  #   ===========
from .c import C_5  #   ===========
from .c import Cs5  #      ========
from .d import D_5  #   ===========
from .d import Ds5  #      ========
from .e import E_5  #   ===========
from .f import F_5  #   ===========
from .f import Fs5  #      ========
from .g import G_5  #   ===========
from .g import Gs5  #      ========
from .a import A_6  #   ===========
from .a import As6  #      ========
from .b import B_6  #   ===========
from .c import C_6  #   ===========
from .c import Cs6  #      ========
from .d import D_6  #   ===========
from .d import Ds6  #      ========
from .e import E_6  #   ===========
from .f import F_6  #   ===========
from .f import Fs6  #      ========
from .g import G_6  #   ===========
from .g import Gs6  #      ========
from .a import A_7  #   ===========
from .a import As7  #      ========
from .b import B_7  #   ===========
from .c import C_7  #   ===========
from .c import Cs7  #      ========
from .d import D_7  #   ===========
from .d import Ds7  #      ========
from .e import E_7  #   ===========
from .f import F_7  #   ===========
from .f import Fs7  #      ========
from .g import G_7  #   ===========
from .g import Gs7  #      ========
from .a import A_8  #   ===========
from .a import As8  #      ========
from .b import B_8  #   ===========
from .c import C_8  #   ===========
from .c import Cs8  #      ========
from .d import D_8  #   ===========
from .d import Ds8  #      ========
from .e import E_8  #   ===========
from .f import F_8  #   ===========
from .f import Fs8  #      ========
from .g import G_8  #   ===========
from .g import Gs8  #      ========
from .a import A_9  #   ===========
from .a import As9  #      ========
from .b import B_9  #   ===========
from .c import C_9  #   ===========
from .c import Cs9  #      ========
from .d import D_9  #   ===========
from .d import Ds9  #      ========
from .e import E_9  #   ===========
from .f import F_9  #   ===========
from .f import Fs9  #      ========
from .g import G_9  #   ===========
from .g import Gs9  #      ========
